sudo: required
services: 
    - docker

before_install:
    - docker build -t vb-george/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vb-george/docker-react npm run test
deploy:
    provider: "elasticbeanstalk"
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-031718800279"
    bucket_path: "docker-react"
    on:
        branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
    